export default {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    // LOGIN_TIENDA_NUBE_REQUEST: 'LOGIN_TIENDA_NUBE_REQUEST',
    // LOGIN_TIENDA_NUBE_SUCCESS: 'LOGIN_TIENDA_NUBE_SUCCESS',
    // LOGIN_TIENDA_NUBE_FAILURE: 'LOGIN_TIENDA_NUBE_FAILURE',
    //
    // LOGIN_VTEX_REQUEST: 'LOGIN_VTEX_REQUEST',
    // LOGIN_VTEX_SUCCESS: 'LOGIN_VTEX_SUCCESS',
    // LOGIN_VTEX_FAILURE: 'LOGIN_VTEX_FAILURE',
    //
    // SIGN_UP_TIENDA_NUBE_REQUEST: 'SIGN_UP_TIENDA_NUBE_REQUEST',
    // SIGN_UP_TIENDA_NUBE_SUCCESS: 'SIGN_UP_TIENDA_NUBE_SUCCESS',
    // SIGN_UP_TIENDA_NUBE_FAILURE: 'SIGN_UP_TIENDA_NUBE_FAILURE',

}
