export default {

    TIENDA_NUBE_STATUS_REQUEST: 'TIENDA_NUBE_STATUS_REQUEST',
    TIENDA_NUBE_STATUS_SUCCESS: 'TIENDA_NUBE_STATUS_SUCCESS',
    TIENDA_NUBE_STATUS_FAILURE: 'TIENDA_NUBE_STATUS_FAILURE',

}
