export default {

    GET_VTEX_DATA_REQUEST: 'GET_VTEX_DATA_REQUEST',
    GET_VTEX_DATA_SUCCESS: 'GET_VTEX_DATA_SUCCESS',
    GET_VTEX_DATA_FAILURE: 'GET_VTEX_DATA_FAILURE',

    STORE_VTEX_DATA_REQUEST: 'STORE_VTEX_DATA_REQUEST',
    STORE_VTEX_DATA_SUCCESS: 'STORE_VTEX_DATA_SUCCESS',
    STORE_VTEX_DATA_FAILURE: 'STORE_VTEX_DATA_FAILURE',

}
